version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: 'test_db'
    volumes:
      - db-store:/var/lib/postgresql/data
      # run: $ docker-compose exec db bash psql -U user -d test_db -f /docker-entrypoint-initdb.d/create_tables.sql
      - ./create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db-store:
